Homebrew: adopt ~/.Brewfile

diff --git a/scripts/brewscript b/scripts/brewscript
--- a/scripts/brewscript
+++ b/scripts/brewscript
@@ -1,146 +1,19 @@
 #!/usr/bin/env bash
 
-# Homebrew brew script
+# install / update Homebrew and all installed formulae
 
-# from https://github.com/mathiasbynens/dotfiles/blob/master/brew.sh
-function keepalive() {
-  sudo -v
-  while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &
-}
-
-function install_homebrew_if_needed() {
-  if ! [ -e '/usr/local/bin/brew' ]; then
-    echo "Homebrew 'brew' binary not found in your PATH. Installing Homebrew..."
-    rm -rf /usr/local/Cellar /usr/local/.git
-    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
-  fi
-}
-
-function run_command() {
-  desc=$1
-  cmd=$2
-  echo "$desc with '$cmd'..."
-  $cmd
-}
-
-function check_or_install_formula() {
-  formula_string=$@
-  elements=( $formula_string )
-  formula=${elements[0]}
-  echo "Checking if '$formula' is installed..."
-  if `brew list $formula >/dev/null 2>&1`; then
-    echo "Formula '$formula' already installed"
-  else
-    echo "Formula '$formula' not yet installed."
-    run_command "Installing '$formula'" "brew install $formula_string"
-  fi
-}
-
-function check_or_install_cask() {
-  cask=$1
-  force=$2
-  installed=0
-  echo "Checking if '$cask' is installed..."
-  if `brew cask list $cask >/dev/null 2>&1`; then
-    echo "Cask '$cask' already installed."
-    installed=1
-  else
-    echo "Cask '$cask' not yet installed."
-  fi
-  if [[ $installed -eq 0 || $force -eq 1 ]]; then
-    cmd="brew cask install"
-    if [ $force -eq 1 ]; then
-      echo "Forcing installation..."
-      cmd="$cmd --force"
-    fi
-    cmd="$cmd $cask"
-    run_command "Installing '$cask'" "$cmd"
-  fi
-}
-
-
-# allow this script to receive --force and pass it along
-force_install=0
-if [ "$1" = '--force' ]; then
-  force_install=1
+if ! [ -e '/usr/local/bin/brew' ]; then
+  echo "Homebrew 'brew' binary not found in your PATH. Installing Homebrew..."
+  rm -rf /usr/local/Cellar /usr/local/.git
+  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
 fi
 
-install_homebrew_if_needed
+if [ -e "$HOME/.Brewfile" ]; then
+  echo 'Installing formulae / apps from ~/.Brewfile'
+  brew bundle --global
+fi
 
-keepalive
-run_command 'Updating Homebrew itself' 'brew update'
-run_command 'Upgrading all installed formulae' 'brew upgrade --without-x11'
-
-declare -a desired_formulae=(awscli
-                             chruby
-                             coreutils
-                             ctags
-                             elixir
-                             'emacs --HEAD --with-cocoa'
-                             findutils
-                             git
-                             gnu-sed
-                             imagemagick
-                             'jmeter --with-plugins'
-                             jq
-                             libxml2
-                             libxslt
-                             libyaml
-                             maven
-                             mongodb
-                             mysql
-                             openssl
-                             python3
-                             ranger
-                             reattach-to-user-namespace
-                             ruby-install
-                             sqlite
-                             the_silver_searcher
-                             tig
-                             tmux
-                             'vim --with-override-system-vi'
-                             watch
-                             w3m
-                             wget
-                             zsh)
-
-# install desired formulae
-for formula in "${desired_formulae[@]}"; do
-  check_or_install_formula $formula
-done
-
-# set up brew cask
-run_command 'Tapping homebrew-cask' 'brew tap caskroom/homebrew-cask'
-check_or_install_formula brew-cask
-# run_command 'Tapping versions' 'brew tap caskroom/versions'
-run_command 'Upgrading brew-cask' 'brew upgrade brew-cask'
-
-declare -a desired_casks=(chefdk
-                          dockertoolbox
-                          dropbox
-                          iterm2-nightly
-                          java
-                          keepingyouawake
-                          kindle
-                          macdown
-                          1password
-                          sequel-pro
-                          slack
-                          vagrant
-                          virtualbox
-                          vlc
-                          wkhtmltopdf)
-
-# install desired casks
-for cask in "${desired_casks[@]}"; do
-  check_or_install_cask $cask $force_install
-done
-
-# these are currently coming from the Mac App Store, not Cask
-# xee
-# clear
-
-# remove old cruft
-run_command 'Cleaning up old formula versions and cache' 'brew cleanup'
-run_command 'Removing dead symlinks' 'brew prune'
-run_command 'Cleaning up old cask content' 'brew cask cleanup'
+echo 'Updating Homebrew itself'
+brew update
+echo 'Upgrading all installed formulae'
+brew upgrade --without-x11
